version: 2
updates:
  - package-ecosystem: "npm" # Bun is not available.
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
    commit-message:
      prefix: "deps"
    auto-merge: true
